"""Provides methods to access various resource files for the application."""

__credits__ = [
    ('AG Multimedia Studio',
     'Green Light Icon (from findicons.com)'),
    ('stock icons iconshock',
     'Connection Icon (from findicons.com)'),
    ('YellowIcon',
     'Motors Icon (from findicons.com)'),
    ('YellowIcon',
     'Integrator Icon (from findicons.com)'),
    ('Woothemes',
     'Magnet Icon (from findicons.com)'),
    ('GraphicRating.com',
     'Results Icon (from findicons.com)'),
    ('refresh-24px.svg',
     'Refresh Icon (from https://material.io/icons/)'),
    ('current-ac.svg',
     'Cycle Icon (from https://materialdesignicons.com/)'),
    ('redo.svg',
     'Send Icon (from https://materialdesignicons.com/)'),
    ('power-24px.svg',
     'Power On Icon (from https://material.io/icons/)'),
    ('power_off-24px.svg',
     'Power Off Icon(from https://material.io/icons/)'),
    ('chart-line.svg',
     'Plot Icon (from https://materialdesignicons.com/)'),
    ('play_circle_outline-24px.svg',
     'Move Icon (from https://material.io/icons/)'),
    ('stop-circle-outline.svg',
     'Stop Icon (from https://materialdesignicons.com/)'),
    ('save-24px.svg',
     'Save Icon (from https://material.io/icons/)'),
    ('database.svg',
     'Database Icon (from https://materialdesignicons.com/)'),
    ('database-plus.svg',
     'Database Plus Icon (from https://materialdesignicons.com/)'),
    ('settings-outline.svg',
     'Settings Icon (from https://materialdesignicons.com/)'),
    ('broom.svg',
     'Clear Icon (from https://materialdesignicons.com/)'),
    ]
